---
# Variable setup.
- name: Include OS-specific variables.
  ansible.builtin.include_vars: "{{ ansible_os_family }}.yml"

- name: Define nginx_user.
  ansible.builtin.set_fact:
    nginx_user: "{{ __nginx_user }}"
  when: nginx_user is not defined

# Setup/install tasks.

- name: Setup Ubuntu
  ansible.builtin.include_tasks: setup-Ubuntu.yml
  when: ansible_distribution == 'Ubuntu'

- name: Setup Debian
  ansible.builtin.include_tasks: setup-Debian.yml
  when: ansible_os_family == 'Debian'

# Vhost configuration.
- name: Template vhost
  ansible.builtin.import_tasks: vhosts.yml

# Nginx setup.
- name: Copy nginx configuration in place.
  ansible.builtin.template:
    src: "{{ nginx_conf_template }}"
    dest: "{{ nginx_conf_file_path }}"
    owner: root
    group: "{{ root_group | default('root') }}"
    mode: '0644'
  notify:
    - Reload nginx

- name: Ensure nginx service is running as configured.
  ansible.builtin.service:
    name: nginx
    state: "{{ nginx_service_state }}"
    enabled: "{{ nginx_service_enabled }}"
