---

- name: "=== HAPROXY === Enable stats"
  ansible.builtin.include_vars: "enable_stats.yml"
  when: haproxy_enable_stats | bool

- name: "=== HAPROXY === Install haproxy package"
  ansible.builtin.apt:
    name: "{{ haproxy_pkg }}"
    state: "present"

- name: "=== HAPROXY === Install haproxy config"
  ansible.builtin.template:
    src: "{{ haproxy_template_config }}"
    dest: "{{ haproxy_path_config }}/{{ haproxy_file_config }}"
    mode: "0644"
  notify: "=== HAPROXY === restart haproxy"

- name: "=== HAPROXY === Enable autostart"
  ansible.builtin.systemd:
    name: "{{ haproxy_service }}"
    enabled: true

...
