---
galaxy_info:
  author: Dmitrii Kashin
  description: haproxy
  role_name: haproxy
  namespace: almaops
  license: MIT
  min_ansible_version: 2.10
  platforms:
    - name: Ubuntu
      versions:
        - all
    - name: Debian
      versions:
        - all
  galaxy_tags:
    - haproxy
dependencies: []
...
