---
galaxy_info:
  author: Dmitrii Kashin
  description: systemd module wrapped into the role
  role_name: systemd
  license: MIT
  min_ansible_version: "2.15"
  galaxy_tags:
    - systemd
allow_duplicates: true
dependencies: []
...
