---
namespace: almaops
name: common
version: 1.0.52
readme: README.md
authors:
  - Valentin Gostev <val@almaops.ru>
  - Dmitrii Kashin <freehck@freehck.com>
description: 'Base Almaops roles'
license:
  - MIT
tags:
  - almaops
  - common
  - application
  - tools
  - database
  - linux
  - storage
dependencies:
  community.general: ">=10.0.0"
  community.docker: '>=4.0.0'
repository: 'https://github.com/almaops/ansible-collection-common'
homepage: 'https://almaops.com'
issues: 'https://github.com/almaops/ansible-collection-common/issues'
build_ignore:
  - .gitignore
  - .yamllint
  - .github
...
