---
namespace: almaops
name: common
version: 1.0.14
readme: README.md
authors:
  - Valentin Gostev <val@almaops.ru>
  - Dmitrii Kashin <freehck@freehck.com>
description: 'Base Almaops roles'
license:
  - MIT
tags:
  - almaops
  - common
dependencies: {}
repository: 'https://github.com/almaops/ansible-collection-common'
homepage: 'https://almaops.com'
issues: 'https://github.com/almaops/ansible-collection-common/issues'
build_ignore:
  - .gitignore
  - .yamllint
...
