---
dependencies: []
galaxy_info:
  role_name: nginx
  author: geerlingguy
  description: Nginx installation for Linux, FreeBSD and OpenBSD.
  company: "Midwestern Mac, LLC"
  license: "license (BSD, MIT)"
  min_ansible_version: "2.15"
  galaxy_tags:
    - development
    - web
    - nginx
    - reverse
    - proxy
    - load
    - balancer
...
