---
# General settings
ct_keycloak_task_prefix: "=== ALMAOPS CT_KEYCLOAK ==="

# Flags
ct_keycloak_enable_jdbc_ping: false

# Path settings
ct_keycloak_path_base: "/srv/{{ ct_keycloak_ct_name }}"

ct_keycloak_path_env: "{{ ct_keycloak_path_base }}"
ct_keycloak_file_env: "env"
ct_keycloak_template_env: "env.j2"

ct_keycloak_path_config: "{{ ct_keycloak_path_base }}/cfg"
ct_keycloak_file_config: "cache-ispn-jdbc-ping.xml"
ct_keycloak_template_config: "cache-ispn-jdbc-ping.xml.j2"

# Network settings
ct_keycloak_bind_addr: "127.0.0.1"
ct_keycloak_bind_port: "8080"
ct_keycloak_bind_ct_port: "8080"

# Container settings
ct_keycloak_ct_image: "quay.io/keycloak/keycloak:26.1"

ct_keycloak_ct_name: "keycloak"
ct_keycloak_ct_restart_policy: "always"
ct_keycloak_ct_pull: "false"
ct_keycloak_ct_recreate: "false"
ct_keycloak_ct_state: "started"
ct_keycloak_ct_restart: "false"

ct_keycloak_ct_ports_main:
  - "{{ ct_keycloak_bind_addr }}:{{ ct_keycloak_bind_port }}:{{ ct_keycloak_bind_ct_port }}"
ct_keycloak_ct_ports_extra: []
ct_keycloak_ct_ports: "{{ ct_keycloak_ct_ports_main + ct_keycloak_ct_ports_extra }}"

ct_keycloak_network_mode: "default" # for jdbc ping it feels sane to use "host" network

ct_keycloak_ct_volumes_jdbc_ping: []
ct_keycloak_ct_volumes_extra: []
ct_keycloak_ct_volumes: "{{ ct_keycloak_ct_volumes_jdbc_ping + ct_keycloak_ct_volumes_extra }}"

ct_keycloak_ct_command: [ "start-dev" ]

ct_keycloak_env:
  KC_BOOTSTRAP_ADMIN_USERNAME: "admin"
  KC_BOOTSTRAP_ADMIN_PASSWORD: "AlmaOps112"
  KC_DB: ""
  KC_DB_URL_HOST: ""
  KC_DB_URL_DATABASE: ""
  KC_DB_USERNAME: ""
  KC_DB_PASSWORD: ""
  KC_LOG_LEVEL: ""
  JGROUPS_DISCOVERY_EXTERNAL_IP: ""
  KC_CACHE_CONFIG_FILE: ""
ct_keycloak_env_extra: {}
  
ct_keycloak_hostname: "{{ inventory_hostname }}"

# docs:
# https://www.keycloak.org/2019/08/keycloak-jdbc-ping
# https://www.keycloak.org/2019/05/keycloak-cluster-setup.html
