---
- name: "=== CRON === create job by crontab schedule"
  ansible.builtin.include_tasks: cronjob_crontab.yml
  when: job.schedule is defined

- name: "=== CRON === create job by ansible schedule"
  ansible.builtin.include_tasks: cronjob_ansible.yml
  when: job.schedule is undefined
...
