
# ct_mongodb



- name: "{{ ct_mongodb_task_prefix }}. Creating a '{{ ct_mongodb_ct_name }}' container"
  docker_container:
    image: "{{ ct_mongodb_ct_image }}:{{ ct_mongodb_ct_version }}"
    name: "{{ ct_mongodb_ct_name }}"
    volumes: "{{ ct_mongodb_ct_volumes }}"
    env: "{{ ct_mongodb_ct_env }}"
    ports: "{{ ct_mongodb_ct_ports }}"
    restart: "{{ ct_mongodb_ct_restart | bool }}"
    restart_policy: "{{ ct_mongodb_ct_restart_policy }}"
    state: "started"
