
# ct_mongodb



- name: "{{ ct_mongodb_task_prefix }}. Creating the '{{ ct_mongodb_out_path_config }}' directory"
  file:
    path: "{{ ct_mongodb_out_path_config }}"
    state: directory
    owner: 1001
    recurse: true



- name: "{{ ct_mongodb_task_prefix }}. Creating a '{{ ct_mongodb_ct_name }}' container"
  docker_container:
    image: "{{ ct_mongodb_ct_image }}:{{ ct_mongodb_ct_version }}"
    name: "{{ ct_mongodb_ct_name }}"
    volumes: "{{ ct_mongodb_ct_volumes }}"
    env: "{{ ct_mongodb_ct_env }}"
    ports: "{{ ct_mongodb_ct_ports }}"
    restart: "{{ ct_mongodb_ct_restart | bool }}"
    restart_policy: "{{ ct_mongodb_ct_restart_policy }}"
    state: "started"
    networks:
      - name: "{{ ct_mongodb_network }}"
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo {{ ct_mongodb_ct_bind_addr }}:{{ ct_mongodb_ct_bind_port }}/test --quiet
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 60s
