---
- name: "{{ ct_mongodb_task_prefix }} Create config directory"
  ansible.builtin.file:
    path: "{{ ct_mongodb_path_config_base }}"
    state: directory
    mode: '0700'
    owner: root
    group: root

- name: "{{ ct_mongodb_task_prefix }} Create env file"
  ansible.builtin.template:
    src: "{{ ct_mongodb_template_env }}"
    dest: "{{ ct_mongodb_path_config_file }}"
    owner: root
    group: root
    mode: '0400'

- name: "{{ ct_mongodb_task_prefix }} Create data directory"
  ansible.builtin.file:
    path: "{{ ct_mongodb_path_data_volume }}"
    state: directory
    mode: '0700'
    owner: root
    group: root

- name: "{{ ct_mongodb_task_prefix }} Provision container"
  community.docker.docker_container:
    env_file: "{{ ct_mongodb_path_config_file }}"
    image: "{{ ct_mongodb_ct_image }}"
    name: "{{ ct_mongodb_ct_name }}"
    ports: "{{ ct_mongodb_ct_ports }}"
    pull: "{{ ct_mongodb_ct_pull }}"
    recreate: "{{ ct_mongodb_ct_recreate }}"
    restart_policy: "{{ ct_mongodb_ct_restart_policy }}"
    state: "{{ ct_mongodb_ct_state }}"
    volumes: "{{ ct_mongodb_ct_volumes }}"
    network_mode: "{{ ct_mongodb_ct_network_mode }}"
...
