---
galaxy_info:
  author: Valentin Gostev
  description: Ansible role deploys Kafka UI container
  role_name: ct_kafka_ui
  namespace: almaops
  license: MIT
  min_ansible_version: 2.12
  platforms:
    - name: Ubuntu
      versions:
        - all
    - name: Debian
      versions:
        - all
  galaxy_tags:
    - kafka
    - kafka-ui
dependencies: []
...
