---

- name: "=== CT GITLAB_RUNNER === Load dond volumes"
  ansible.builtin.include_vars: "dond_volumes.yml"
  when: ct_gitlab_runner_dond_enabled | bool

- name: "=== CT GITLAB_RUNNER === Create directory {{ ct_gitlab_runner_path_cfg_dir }}"
  ansible.builtin.file:
    path: "{{ ct_gitlab_runner_path_cfg_dir }}"
    state: directory
    mode: '0755'
    recurse: true
  changed_when: false

- name: "=== CT GITLAB_RUNNER === Provision container {{ ct_gitlab_runner_ct_name }}"
  community.docker.docker_container:
    name: "{{ ct_gitlab_runner_ct_name }}"
    image: "{{ ct_gitlab_runner_ct_image }}"
    ports: "{{ ct_gitlab_runner_ct_ports }}"
    volumes: "{{ ct_gitlab_runner_ct_volumes }}"
    env: "{{ ct_gitlab_runner_ct_env }}"
    restart_policy: "{{ ct_gitlab_runner_ct_restart_policy }}"
    state: "{{ ct_gitlab_runner_ct_state }}"
    restart: "{{ ct_gitlab_runner_ct_restart | bool }}"
    pull: "{{ ct_gitlab_runner_ct_pull | bool }}"
    recreate: "{{ ct_gitlab_runner_ct_recreate | bool }}"
    etc_hosts: "{{ ct_gitlab_runner_ct_etc_hosts }}"

- name: "=== CT GITLAB_RUNNER === Check if runner is already registered - {{ ct_gitlab_runner_name }}"
  ansible.builtin.stat:
    path: "{{ ct_gitlab_runner_path_cfg }}"
  register: ct_gitlab_runner_path_cfg_file

- name: "=== CT GITLAB_RUNNER === Register runner {{ ct_gitlab_runner_name }}"
  ansible.builtin.shell: >
    docker exec {{ ct_gitlab_runner_ct_name }} gitlab-runner unregister --all-runners;
    docker exec {{ ct_gitlab_runner_ct_name }} gitlab-runner register
    --non-interactive
    --url '{{ ct_gitlab_runner_coordinator_url }}'
    --registration-token '{{ ct_gitlab_runner_registration_token }}'
    --description '{{ ct_gitlab_runner_name }}'
    --tag-list '{{ ct_gitlab_runner_tags | join(",") }}'
    --executor '{{ ct_gitlab_runner_executor }}'
    --limit '{{ ct_gitlab_runner_parallel_builds_number }}'
    --docker-image '{{ ct_gitlab_runner_docker_image }}'
    --run-untagged='{{ ct_gitlab_runner_run_untagged }}'
    {% if ct_gitlab_runner_cache_s3_enabled %}
    --cache-s3-server-address '{{ ct_gitlab_runner_cache_s3_server_address }}'
    --cache-s3-access-key '{{ ct_gitlab_runner_cache_s3_access_key }}'
    --cache-s3-secret-key '{{ ct_gitlab_runner_cache_s3_secret_key }}'
    {% endif %}
    {% if ct_gitlab_runner_dind_enabled %}
    --docker-privileged
    {% endif %}
    {% for volume in ct_gitlab_runner_docker_volumes %}
    --docker-volumes "{{ volume }}"
    {% endfor %}
  when: (not ct_gitlab_runner_path_cfg_file.stat.exists) or ct_gitlab_runner_force_reg
  changed_when: false

- name: "=== CT GITLAB_RUNNER === Set runner concurrency to {{ ct_gitlab_runner_parallel_builds_number }}"
  ansible.builtin.lineinfile:
    path: "{{ ct_gitlab_runner_path_cfg }}"
    regexp: '^concurrent'
    line: 'concurrent = {{ ct_gitlab_runner_parallel_builds_number }}'
  register: ct_gitlab_runner_path_cfg_file_status

- name: "=== CT GITLAB_RUNNER === Restart runner to apply concurrency settings"
  community.docker.docker_container:
    name: "{{ ct_gitlab_runner_ct_name }}"
    restart: true
  when: ct_gitlab_runner_path_cfg_file_status is changed
