---
- name: Install from package
  ansible.builtin.import_tasks: install-with-package.yml
  when: certbot_install_method == 'package'

- name: Install with snap
  ansible.builtin.import_tasks: install-with-snap.yml
  when: certbot_install_method == 'snap'

- name: Install from source
  ansible.builtin.import_tasks: install-from-source.yml
  when: certbot_install_method == 'source'

- name: Create cert in standalone mode
  ansible.builtin.include_tasks: create-cert-standalone.yml
  with_items: "{{ certbot_certs }}"
  when:
    - certbot_create_if_missing
    - certbot_create_method == 'standalone'
  loop_control:
    loop_var: cert_item

- name: Create cert with webroot
  ansible.builtin.include_tasks: create-cert-webroot.yml
  with_items: "{{ certbot_certs }}"
  when:
    - certbot_create_if_missing
    - certbot_create_method == 'webroot'
  loop_control:
    loop_var: cert_item

- name: Create cert with Cloudflare DNS
  ansible.builtin.include_tasks: create-cert-cloudflare.yml
  with_items: "{{ certbot_certs }}"
  when:
    - certbot_create_if_missing
    - certbot_create_method == 'dns-cloudflare'
  loop_control:
    loop_var: cert_item

- name: Configure renewal by cron
  ansible.builtin.import_tasks: renew-cron.yml
  when: certbot_auto_renew
