---
dependencies: []

galaxy_info:
  role_name: certbot
  author: geerlingguy
  description: "Installs and configures Certbot (for Let's Encrypt)."
  company: "Midwestern Mac, LLC"
  license: "license (BSD, MIT)"
  min_ansible_version: "2.15"
  galaxy_tags:
    - networking
    - system
    - web
    - certbot
    - letsencrypt
    - encryption
    - certificates
    - ssl
    - https
