---
galaxy_info:
  author: Dmitrii Kashin
  description: mysql container
  role_name: ct_mysql
  namespace: almaops
  license: MIT
  min_ansible_version: 2.10
  platforms:
    - name: Ubuntu
      versions:
        - all
    - name: Debian
      versions:
        - all
  galaxy_tags:
    - mysql
dependencies: []
...
