galaxy_info:
  author: Dmitrii Kashin
  description: deploy gitlab-runner in docker container and register it 
  role_name: ct_gitlab_runner
  license: MIT
  min_ansible_version: 2.4
  platforms:
    - name: Ubuntu
      versions:
        - all
    - name: Debian
      versions:
        - all

  galaxy_tags:
    - gitlab
    - gitlab-runner
    - docker

dependencies: []
