---
# General settings
ct_mongodb_task_prefix: "=== CT_MONGODB ==="

# Templates
ct_mongodb_template_env: "mongodb.env.j2"

# Path settings - Configuration file
ct_mongodb_path_config_base: "/etc/ct_mongodb"
ct_mongodb_path_config_file: "{{ ct_mongodb_path_config_base }}/{{ ct_mongodb_ct_name }}.env"

# Path settings - Data directory
ct_mongodb_path_data_base: "/srv/ct_mongodb"
ct_mongodb_path_data_volume: "{{ ct_mongodb_path_data_base }}/{{ ct_mongodb_ct_name }}"
# ct_mongodb_path_data_volume_owner: "1001"
# ct_mongodb_path_ct_data_dbms_dir: "/bitnami/mongodb"
ct_mongodb_path_ct_data: "{{ ct_mongodb_path_ct_data_dbms_dir }}"

# Network settings
ct_mongodb_bind_addr: "127.0.0.1"
ct_mongodb_bind_port: "27017"
ct_mongodb_bind_ct_port: "27017"

# Container settings - general
# ct_mongodb_ct_version: "latest"
# ct_mongodb_ct_image: "bitnami/mongodb:{{ ct_mongodb_ct_version }}"
ct_mongodb_ct_name: "mongodb"
ct_mongodb_ct_volume_data:
  - "{{ ct_mongodb_path_data_volume }}:{{ ct_mongodb_path_ct_data }}"
ct_mongodb_ct_volume_extra: []
ct_mongodb_ct_volumes: "{{ ct_mongodb_ct_volume_data + ct_mongodb_ct_volume_extra }}"
ct_mongodb_ct_ports:
  - "{{ ct_mongodb_bind_addr }}:{{ ct_mongodb_bind_port }}:{{ ct_mongodb_bind_ct_port }}"
ct_mongodb_ct_ports_extra: []
ct_mongodb_ct_pull: "false"
ct_mongodb_ct_recreate: "false"
ct_mongodb_ct_restart_policy: "always"
ct_mongodb_ct_restart: "false"
ct_mongodb_ct_state: "started"
ct_mongodb_ct_network_mode: "default"
ct_mongodb_ct_networks: []

# Environment variables
# ct_mongodb_env_mongodb_initdb_root_username: "root"
# ct_mongodb_env_mongodb_initdb_root_password: "changeme"
ct_mongodb_env_mongodb_port_number: "{{ ct_mongodb_bind_ct_port }}"
ct_mongodb_env_mongodb_enable_journal: "true"
ct_mongodb_env_extra: {}
...
