---
galaxy_info:
  author: Dmitrii Kashin
  description: install packages
  role_name: pkg_install
  namespace: almaops
  license: MIT
  min_ansible_version: "2.15"
  galaxy_tags:
    - system
    - package
    - install
    - apt
    - yum
    - dnf
allow_duplicates: true
dependencies: []
...
