---

## tags: init-ct-keycloak
#- ansible.builtin.import_playbook: almaops.common.11_ct_keycloak

- hosts:
    - "{{ lookup('env', 'CLIENT_LABEL') | default('CLIENT_LABEL', true) }}_env_{{ deploy_target }}_ct_keycloak"
  tags:
    - init-ct-keycloak                  
  become: true
  roles:
    - role: almaops.common.ct_keycloak

...
