---

## tags: certbot nginx
# - ansible.builtin.import_playbook: almaops.common.90_nginx

- name: Configure nginx
  hosts:
    - "{{ lookup('env', 'CLIENT_LABEL') | default('CLIENT_LABEL', true) }}_env_{{ deploy_target | default('') }}_nginx"
  become: true
  roles:

    # install certbot
    - role: almaops.common.certbot
      tags:
        - certbot

    # configure nginx
    - role: almaops.common.nginx
      tags:
        - nginx

...
