---

## tags: haproxy
# - ansible.builtin.import_playbook: almaops.common.91_haproxy

- name: Deploy Haproxy
  hosts:
    - "{{ lookup('env', 'CLIENT_LABEL') | default('CLIENT_LABEL', true) }}_env_{{ deploy_target | default('') }}_haproxy"
  become: true
  roles:
    - role: almaops.common.haproxy
      tags:
        - haproxy

...
