---
name: ansible-lint
on:
  push:
    branched: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    name: Ansible Lint
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Run ansible-lint
        uses: ansible/ansible-lint@main
        # optional (see below):
        with:
          args: "--exclude .ansible"
          setup_python: "true"
          working_directory: ""
          requirements_file: ""
...
