---
name: Publish collection to Ansible Galaxy
on:
  release:
    types:
      - released
jobs:
  deploy:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Deploy the collection
        uses: artis3n/ansible_galaxy_collection@f6110aef877db4caaa7e9a192975fb006dea61fe # v2
        with:
          api_key: ${{ secrets.GALAXY_API_KEY }}
          galaxy_version: ${{ github.event.release.tag_name }}
      # checkout master instead of the release-tag so we can push the galaxy.yml
      - uses: actions/checkout@v4
        with:
          ref: main
      - name: update galaxy.yml with new version
        uses: microsoft/variable-substitution@6287962da9e5b6e68778dc51e840caa03ca84495 # v1
        with:
          files: 'galaxy.yml'
        env:
          version: "${{ github.event.release.tag_name }}"
      - name: push galaxy.yml
        uses: github-actions-x/commit@722d56b8968bf00ced78407bbe2ead81062d8baa # v2.9
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          push-branch: 'main'
          commit-message: 'update galaxy.yml with new version'
          force-add: 'true'
          files: galaxy.yml
          name: AlmaOps CI
          email: info@almaops.com
...
