---
galaxy_info:
  author: Dmitrii Kashin
  description: install and configure docker daemon
  role_name: docker
  license: MIT
  min_ansible_version: "2.15"
  galaxy_tags:
    - docker
dependencies: []
...
